version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: thinktank
      MYSQL_USER: thinktank
      MYSQL_PASSWORD: thinktank_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn thinktank.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=thinktank.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=thinktank
      - DATABASE_USER=thinktank
      - DATABASE_PASSWORD=thinktank_password
      - SECRET_KEY=replace-me
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_STORAGE_BUCKET_NAME=
    depends_on:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
