# Generated by Django 4.2.23 on 2025-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='free_preview',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
    ]
